

"use client"

import { BorderStyleOutlined } from '@mui/icons-material';
import { GlobalStyles, styled } from '@mui/material';
import { Inter } from 'next/font/google'





const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Body = styled("body")(({ theme }) => ({
  root: {
    margin: 0,
    [theme.breakpoints.down("xs")]: {
      margin: 0,
    },
  },
}));



export default function RootLayout({ children,}: {children: React.ReactNode}) {
  return (
   
    <html lang="en">
 <Body className={inter.className}>
   
  
    { children}

    
        </Body>
    </html>
 
  )
}
